### PR TITLE
Update sc-include, polymer & uniform, add `slot-all` to starcounter.html

### PR DESCRIPTION
**Pull request by tomalec**
- Reduce FOUC for links in shadow DOM compositions, 
  Make non-namespaced view-model warning more intrusive

  Update dependencies
    - Juicy/imported-template@3.4.0,
    - Starcounter/starcounter-include@5.2.0
    - Juicy/enlighted-link@0.1.0
    - Polymer/polymer@2.6.1
    - webcomponents/webcomponentsjs@1.2.7

- Add Juicy/slot-all to `starcounter.html`
- Update Uniform (Vaadin elements), palindrom-redirect, and shady-css

### CODE REVIEW

**Comment by tomalec** [comment]
TC tests requires https://github.com/Starcounter/UniformDocs/pull/376 to pass

**Comment by tomalec** [comment]
They are failing as they were for the master https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_UniformDocs_UniformDocsMaster24branchWithStarcounterDevelopNightly&branch_Apps_UniformDocs=%3Cdefault%3E&tab=buildTypeStatusDiv However, locally it passes. I'll wait with the release for BrowserStack setup

**Comment by tomalec** [comment]
@warpech Given the flaky tests that are failing on old-setup, BrowserStack, with this and master branch, I think we should merge it.

**Comment by warpech** [comment]
UniformDocs BrowserStack PR was merged to `master` and is now being tested: https://teamcity.starcounter.org/viewLog.html?buildId=69594&tab=buildResultsDiv&buildTypeId=Apps_UniformDocs_UniformDocsMaster24branchWithStarcounterDevelopNightly

After that, I would like to try testing this PR again, maybe we will be lucky this time?

**Comment by warpech** [comment]
The above build passed. @tomalec has triggered a new build of SCF `3.x-update-sc-include-polymer` here: https://teamcity.starcounter.org/viewLog.html?buildId=69603&tab=buildResultsDiv&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps

**Comment by warpech** [comment]
The build passed on TC. @tomalec it is hard to say why two date picker tests `DatepickerPage_SelectDate` are failing on your PC. They passed both locally for me and for TeamCity.

I think we should continue with the release of SCF. Could you pls do that?

**Review by warpech — APPROVED** [review]
I reviewed the update libraries as well as made a quick smoke test in Chrome. Looks ok!

**Pull request merged**
