### PR TITLE
Preparation for SCF 3.0.0-rc.6

### PR DESCRIPTION
**Pull request by warpech**
This should include Underwear 0.0.3 and Uniform 0.0.5, but for now I am putting Uniform 0.0.4 to it. 

Please don't review yet.

### CODE REVIEW

**Comment by warpech** [comment]
I updated the PR with Underwear 0.0.3 and Uniform 0.0.5.

@PatrykSzwer please review with the current code in BE.

**Comment by tomalec** [comment]
I have bumped Underwear@0.04 and Uniform@0.0.6, I believe it's ready for the review.

**Comment by warpech** [comment]
As this is our first public release to Starcounter 2.4, I would like everyone on the team to do the review with [KitchenSink](https://github.com/Starcounter/KitchenSink/pull/241) and [Blending](https://github.com/Starcounter/Blending/issues/50). Thanks!

**Comment by alshakero** [comment]
Wow. I haven't seen KitchenSink in a long time and was surprised how beautiful it looks now! Seriously felt soooo good to see all the work showing. 

Found:

1. Issue in underwear https://github.com/Starcounter/underwear.css/issues/50. PR in https://github.com/Starcounter/underwear.css/issues/51.
2. Issue in underwear https://github.com/Starcounter/underwear.css/issues/52. PR in https://github.com/Starcounter/underwear.css/issues/51.

Everything else is on point!

**Comment by alshakero** [comment]
Reviewed Blending suite and all looks good except this:

image


Not sure if related though.

**Comment by warpech** [comment]
Thanks @alshakero. All these fixes are cosmetic and don't have to delay the initial release, unless there is some serious problem, I will release it as is tonight. 

Please continue reviewing the docs and apps, thanks!

**Comment by alshakero** [comment]
I fixed issues in https://github.com/Starcounter/StarcounterClientFiles/pull/44#issuecomment-366734859, released underwear.css#0.0.5 and pushed a commit here.

**Pull request merged**
