### PR TITLE
Remove package-lock.json files from bower deps

### PR DESCRIPTION
**Pull request by alshakero**
I think this is a harmless solution around GitHub security warnings. Anything that is vulnerable and we have power over will be in `package.json` files. Other than that it's the package owner responsibility.

### CODE REVIEW

**Comment by warpech** [comment]
It is a weird fix but not that bad actually. Shouldn't we also remove `package.json`? Anyway, I am approving

**Review by warpech — APPROVED** [review]

**Review by tomalec — APPROVED** [review]

**Comment by alshakero** [comment]
> Shouldn't we also remove package.json

I think let's do that if this fails. I have a feeling that this one will be enough. Because it liberates us from the audits of `devDependancies`. `package-lock.json` made GitHub think we have all devDeps installed. And these are literally thousands.

**Comment by tomalec** [comment]
Theoretically if `package.json` is not ignored by package's `bower.json`, somebody in the app could go to the bower package folder and do `npm install` installing vulnerable thingy.

Maybe we can go other way around, and add `package.json` to bower ignores?

**Comment by alshakero** [comment]
> Maybe we can go other way around, and add package.json to bower ignores?

That's reasonable too.

**Pull request merged**
