### PR TITLE
Make npm optional

### PR DESCRIPTION
**Pull request by alshakero**
Fix https://github.com/Starcounter/StarcounterClientFiles/issues/58

### CODE REVIEW

**Review by ubbeK — APPROVED** [review]
Looks good to my eyes, but I haven't tested it. Feel free to merge if you have tested it.

**Comment by alshakero** [comment]
Yes I have.

**Comment by ubbeK** [comment]
Then, go ahead =)

**Comment by alshakero** [comment]
I was waiting for the tests but they won't run given the branch name :( 

I'll send another PR. 😢

**Comment by alshakero** [comment]
Closing in favour of https://github.com/Starcounter/StarcounterClientFiles/pull/66

**Pull request closed without merging**
