### PR TITLE
Checking TC commit status publisher

### PR DESCRIPTION
**Pull request by ubbeK**
DO NOT MERGE THIS

https://github.com/Starcounter/StarcounterClientFiles/issues/121

### CODE REVIEW

**Comment by alshakero** [comment]
Never wanted to merge a PR this bad.

**Comment by ubbeK** [comment]
Feel free to do so but then please revert it =P

**Comment by ubbeK** [comment]
Closing PR as the functionality now works

**Comment by ubbeK** [comment]
@alshakero You missed your chance to merge it =)

**Pull request closed without merging**
