### PR TITLE
Vulcanize without depending on SWs

### PR DESCRIPTION
**Pull request by alshakero**
I think I have tried every possible combination. I tried at least 10 combinations and it just won't get any faster than this with just vulcanizing. However, I'm still a tad thrilled about the 5 seconds we saved.

### CODE REVIEW

**Comment by tomalec** [comment]
Do I get it right, that it just creates two bundles:
- `polymer.html` - with all polymer deps resolved and vulcanized,
- `starcounter.html` - with `palindrom-client` and `starcounter-include`?

What is the performance gain out of it in numbers?

**Comment by alshakero** [comment]
> starcounter.html - with palindrom-client and starcounter-include?

Not this isn't a bundle. I just moved `starcounter-include` import from the app-shell since `starcounter.html` is already included. This didn't result in any perf gains. But it's cleaner so I kept it.

> What is the performance gain out of it in numbers?

Sorry I didn't mention the numbers. Now it's 7.34 seconds with this setup. Down from 12.2.

**Comment by tomalec** [comment]
So the only downside of this PR is that if somebody would like to import any piece of `polymer.html` it will result in an error, isn't it?

**Comment by alshakero** [comment]
No it won't because the browser will not fetch it again. This PR has no downsides because it doesn't bundle `juicy-html`. Nor it will cluster elements that will be fetched individually later. 

The only compromise is that we'll have to fetch `juicy-html`, `imported-template` and `starcounter-include` each individually.

**Review by warpech — APPROVED** [review]
We can still fine tune it, but it looks good to me.

**Review by tomalec — APPROVED** [review]

**Comment by warpech** [comment]
Tests are passing, Lgtm.

This will be SCF 3.0.0

**Pull request merged**
