### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by alshakero**
- `palindrom-client` to 7.2.1
- `uniform.css` to 0.9.0
- `juicy-popover` to 2.1.0
- `vaadin-date-picker` to 3.3.1
- `vaadin-control-state-mixin` to 2.1.2
- `vaadin-lumo-styles` to 1.3.3
- `vaadin-text-field` to 2.1.4

Motivation is to support `compact` mode in `juicy-popover` and fix concern mentioned in https://github.com/Starcounter/uniform/pull/217#pullrequestreview-175365818

### CODE REVIEW

**Comment by warpech** [comment]
The test configuration was recently broken by me. I am working to fix it. New build triggered: https://teamcity.starcounter.org/viewQueued.html?itemId=78993

**Comment by warpech** [comment]
Pagination-related tests are failing. @alshakero can you pls take a look? https://teamcity.starcounter.org/viewLog.html?buildId=78993&

**Comment by alshakero** [comment]
Most likely it will pass. The culprit is no longer failing. 
https://teamcity.starcounter.org/viewLog.html?buildId=79697&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps&tab=buildResultsDiv

**Comment by warpech** [comment]
> Most likely it will pass. The culprit is no longer failing.
teamcity.starcounter.org/viewLog.html?buildId=79697&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps&tab=buildResultsDiv

The link leads to a build that was not a build of this PR. It was a build of 4bee4f1aa03aaf50a18ac157f23e91621a2c4e01 (current `3.x`).

I have triggered a build of this PR: https://teamcity.starcounter.org/viewQueued.html?itemId=79707

Meanwhile, can you solve the conflict with current `3.x`?

**Pull request merged**
