### PR TITLE
3.x handle palindrom error in appshell and update palindrom-error-catcher

### PR DESCRIPTION
**Pull request by alshakero**
Fixes #87 and updates palindrom-error-catcher

### CODE REVIEW

**Comment by tomalec** [comment]
Why not add it to https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/src/StarcounterClientFiles/wwwroot/sys/starcounter.html with other inline scripts and closer to the `palindrom-client` import?

**Comment by alshakero** [comment]
> Why not add it to /src/StarcounterClientFiles/wwwroot/sys/starcounter.html@3.x with other inline scripts and closer to the palindrom-client import?

I like this. It also allows people to create their own `starcounter.html` and put it in `sys` if they wanted to.

**Review by warpech — APPROVED** [review]

**Comment by tomalec** [comment]
Do you have any idea where to put tests for this? (like ones from https://github.com/Palindrom/palindrom-error-catcher/pull/5/files ) 
KitchenSink, new SCF tests, or just forget about it?

**Comment by alshakero** [comment]
> Do you have any idea where to put tests for this? (like ones from Palindrom/palindrom-error-catcher/pull/5/files )

I think the only sensical place is SCF itself. But there isn't even a tests project. And I'm not sure if it's worth it. I'm willing to create a small endpoint in SCF, sth like `/tests-page-for-palindrom-client-log-message/` and test against it, if you see value in that. I personally don't.

**Comment by warpech** [comment]
Tests for `palindrom-error-catcher` should be in `palindrom-error-catcher` repo, tests for `app-shell.html` should be in SCF repo.

Integration tests for what happens after server dies might be in KitchenSink, but good luck killing Starcounter from Selenium and then bringing it back for another test :)

I think we should not focus on it now. Similarly to how Starcounter DevTools do not have tests. We will afford that when we are 3x bigger.

**Pull request merged**
