### PR TITLE
Update Juicy/imported-template@3.3.0 and Palindrom@5.1.3

### PR DESCRIPTION
**Pull request by tomalec**
Removes chromium bug workaround https://github.com/Juicy/imported-template/issues/55,
makes the flow more synchronous,
reduces the reasons of FOUC

### CODE REVIEW

**Comment by alshakero** [comment]
I'll push a commit in a few mins to update Palindrom (with new JSONPatcherProxy and JSON-Patch).

**Review by alshakero — APPROVED** [review]
LGTM

**Comment by alshakero** [comment]
Wow sorry. I promised you to release and forgot, right?

**Comment by tomalec** [comment]
NP, I forgot you promised ;)

**Pull request merged**
