### PR TITLE
Document releasing a version

### PR DESCRIPTION
**Pull request by alshakero**
Fix https://github.com/Starcounter/StarcounterClientFiles/issues/63

### CODE REVIEW

**Comment by alshakero** [comment]
Oh, I've just seen this https://github.com/Starcounter/AdminTrack/issues/476. Updating in a minute.

**Comment by ubbeK** [comment]
Done with your changes?

**Comment by alshakero** [comment]
Yes sir.

**Review by ubbeK — APPROVED** [review]

**Comment by tomalec** [comment]
How this peroces from README.md is integrated with one from CONTRIBUTING? https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/CONTRIBUTING.md#releasing-of-a-new-version-of-starcounterclientfiles-3x

**Comment by warpech** [comment]
Good find, @tomalec. I made an issue : https://github.com/Starcounter/StarcounterClientFiles/issues/67

**Pull request merged**
