### PR TITLE
Update palindrom version to 6.0.1

### PR DESCRIPTION
**Pull request by alshakero**
See https://github.com/Palindrom/palindrom/releases

Fixes branch name in https://github.com/Starcounter/StarcounterClientFiles/pull/134

### CODE REVIEW

**Comment by warpech** [comment]
I have restarted a build that failed due to bad config: https://teamcity.starcounter.org/viewLog.html?buildId=94314&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps

**Comment by warpech** [comment]
Failed, restarting: https://teamcity.starcounter.org/viewQueued.html?itemId=94317

**Comment by warpech** [comment]
It keeps failing. I have revived a thread on Slack: https://starcounter.slack.com/archives/C5Q4Y78F5/p1553845774000400

**Comment by warpech** [comment]
I removed `work` and `temp` directories, rebooted the build agent and started again: https://teamcity.starcounter.org/viewLog.html?buildId=94324&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps

**Comment by alshakero** [comment]
This PR is blocked by NuGet space limit. I get this error why I try to push the package:

```
Response status code does not indicate success: 413 (The package size for file 'package.nupkg' is too large. The feed owner may have to upgrade the MyGet subscription to resolve this issue.).
An error occurred when executing task 'PushClientFiles'.
Error: One or more errors occurred. (NuGet: Process returned an error (exit code 1).)
        NuGet: Process returned an error (exit code 1).
```

**Comment by warpech** [comment]
To be specific, this is MyGet space limit. It is discussed in the Slack thread: https://starcounter.slack.com/archives/C5Q4Y78F5/p1554476253064100

**Comment by alshakero** [comment]
Merging as SCF is now published on NuGet, Starcounter Warehouse, and here on GitHub.

**Pull request merged**
