### PR TITLE
Fix underwear path in app-shell

### LINKED ISSUE #100: Update `underwear.css` patch in app-shell
Currently SCF fetches `underwear.css` from `/sys/underwear.css` which is not valid anymore. It needs to fetch it from `/sys/uniform.css/dist/underwear.css`.

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: https://github.com/Starcounter/StarcounterClientFiles/issues/100

I tested it and it fixed the issue.

### CODE REVIEW

**Review by warpech — APPROVED** [review]
Tested with UniformDocs, LGTM

**Comment by warpech** [comment]
There is an ongoing test: https://teamcity.starcounter.org/viewLog.html?buildId=60785&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps. It seems it will fail. Any idea why?

**Comment by alshakero** [comment]
Not really. But it's surely unrelated to this PR.

**Comment by alshakero** [comment]
Since it's unrelated I'll release to fix the issue ASAP.

**Pull request merged**
