### PR TITLE
Use NuGet instead of MyGet

### PR DESCRIPTION
**Pull request by alshakero**
Changed publishing script to publish on NuGet instead of MyGet. Tested and all works. 

Also with help from @per-samuelsson, SCF is now unlisted on MyGet so NuGet will take precedence when Starcounter.ClientFiles package is fetched by `level1`. 

I'll update our passwords file with the creds of the NuGet account I created.

### CODE REVIEW

**Comment by per-samuelsson** [comment]
> I'll update our passwords file with the creds of the NuGet account I created.

What does this mean? That client files are not under our Starcounter account?

**Comment by alshakero** [comment]
> That client files are not under our Starcounter account?

It is now.

**Review by warpech — APPROVED** [review]
Code looks OK. I did not test it manually like you did.

Approving, but shouldn't this PR be targeted at https://github.com/Starcounter/StarcounterClientFiles/pull/135?

**Comment by alshakero** [comment]
> Approving, but shouldn't this PR be targeted at #135?

I went out of my way to make them sepearte because I thought they're very different concerns and I thought MyGet -> NuGet change should be well-documented on its own.

**Pull request merged**
