### PR TITLE
Update Starcounter/Uniform@0.7.0 and Palindrom/palindrom-client@7.2.0

### PR DESCRIPTION
**Pull request by tomalec**
Uniform https://github.com/Starcounter/uniform.css/releases
 - New sizing behavior of `uni-form-item`,
 - Ability to make anchors look like buttons,
 - Removed support for .uni-label-control,
 - Use relative path to uniform.css in uni-data-table,
 - Fix uniform.css path in uni-data-table

Palindrom-client https://github.com/Palindrom/palindrom-client/releases
 - Reset state behavior changed

### CODE REVIEW

**Comment by tomalec** [comment]
The test that is failing in TC is failing at my local machine even for the older version of SCF, there fore I'm not sure if I should bother about it.

**Comment by tomalec** [comment]
Re-run made the tests green https://teamcity.starcounter.org/viewLog.html?buildId=70146&tab=buildResultsDiv&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps PR ready for the review.

**Review by alshakero — APPROVED** [review]
Looks great to me.

**Comment by alshakero** [comment]
Closing in favour of #124

**Pull request closed without merging**
